### ISSUE TITLE
Doesn't work on latest LOVE v0.10.1

### ISSUE THREAD

**Issue by dns** [Ranguna/DRUGLIFE#1]
The game just showing black screen when running on latest LOVE v0.10.1,

**Comment by Ranguna** [comment]
Probably yeah, the last commit was in 2013.
I abandoned this project and the code is really messy since I wrote it when I was starting to learn lua.
I probably won't work on this for the time being, I'm currently developing a simulator game but you can pick this up if you want, I really don't recommend it thought :laughing:

**Comment by dns** [comment]
I want to ask something about your Asteroid game on Android.
I want to reuse Love splashscreen logo ("made with Love + animation"). Do made it by yourself? is that splashscreen opensource?

**Comment by Ranguna** [comment]
You should've asked that on ASS's post on the forum, the splash was not open source but I see no reason not to publish it so now you can find it [here](https://love2d.org/forums/viewtopic.php?f=3&t=81776&p=200137#p200137), it's all your, feel free to use it however you want :+1:

**Comment by dns** [comment]
Thanks, that's awesome.

**Comment by Ranguna** [comment]
You are welcome.
